### ISSUE TITLE
RemoteEvents don't function correctly when using rbxnet

### ISSUE THREAD

**Issue by std-cin** [Michael-48/Iris#34]
Unsure whether it's my issue or not, but any request gets rejected when using Iris to send it.
Button code:
```lua
if Iris.Button({ "Button" }).clicked() then
    local remote = remotes.Client:Get("PrintMessage")
    remote:SendToServer("This should be printed")
end
``` 
Server-side code:
```lua
remotes.Server:Get("PrintMessage"):Connect(function(plr, message)
	print(message)
end)
```
Error itself:
``net.out.definitions.ClientDefinitionBuilder:54: Expected Promise rejected with no value.``
Everything works perfectly fine when using a vanilla Roblox button and the message gets printed.

Rbxnet: https://rbxnet.australis.dev/

**Comment by JakeyWasTaken** [comment]
Seems more like an rbxnet issue

**Comment by SirMallard** [comment]
I tried having a look at the documentation for RBXNet but I wasn't quite sure how it works. Within the Iris loop, there shouldn't be any asynchronous code which would prevent the entire code from finishing. I presume that would be the issue, but I'm not quite sure. I'll see if I can do some testing with this.

**Comment by Michael-48** [comment]
This appears to be intended behavior. In an Iris execution cycle, a coroutine is spawned and if its lifecycle is not concluded when the next Iris cycle is initialized, then the coroutine is ended. In most scenarios involving asynchronous code inside of an Iris cycle it is best practice to spawn a thread and keep all GUI code synchronous.
