### ISSUE TITLE
Iris.InputTextMultiline

### ISSUE THREAD

**Issue by SirMallard** [Michael-48/Iris#40]

**Comment by Michael-48** [comment]
Updating this issue to reflect the way ImGui handles multiline text input. In ImGui it is its own function, `ImGui::InputTextMultiline()`. This is probably better because it has an additional argument, `const ImVec2& size = ImVec2(0, 0)` which determines its size in characters.

**Comment by SirMallard** [comment]
This has been fixed with the addition of the `ContentHeight` config option, which now sets a minimum size for certain widgets. Additionally, ReadOnly and MultiLine arguments have been added to `Iris.InpuText` which should cover everything needed by this.
