### ISSUE TITLE
Fixed window update latency issue.

### ISSUE THREAD

**Issue by Michael-48** [Michael-48/Iris#46]
As originally fixed in 6fcbfa2, then reverted in b6e4cc3, this should not be fixed until UIFlexItems are released from beta by Roblox, because this change breaks the interoperability between Beta and Non-Beta versions of roblox which exist currently.

**Comment by SirMallard** [comment]
I've also changed the window title to use UIFlexItems, so I'll link it here for when it's out of beta. #title-flex

**Comment by SirMallard** [comment]
Seeing as Flex has been released to clients, I think we can start using them regularly. I'll push everything through with this then.
