### ISSUE TITLE
widgets.getMouseLocation Returning Incorrect Values

### ISSUE THREAD

**Issue by TheyCallMeRyan** [Michael-48/Iris#54]
It looks like GuiService doesn't immediately return the correct value for GetGuiInset. Because of this, the MouseLocation is always wrong for the isPosInsideRect checks in Menu / Window / Combo if you loaded too soon. In my case this leads to Menus never functioning as I consistently load too early in studio.

![image](https://github.com/Michael-48/Iris/assets/15707012/6c9331d3-d6d6-4c57-b32b-4d13213f055c)
![image](https://github.com/Michael-48/Iris/assets/15707012/a42e829a-f454-4d32-8daa-8acbe12fb1ae)

**Comment by SirMallard** [comment]
Should be merged now, thanks for finding and fixing this.
