### ISSUE TITLE
:Disconnect method for Iris:Connect and State:OnChange objects

### ISSUE THREAD

**Issue by Michael-48** [Michael-48/Iris#57]

**Comment by SirMallard** [comment]
Should be fixed here: #95e9232

**Comment by Michael-48** [comment]
This is probably the better way to do this. A table with nothing except a Disconnect method just for the sake of consistency with RBXScriptConnection instances is overkill now that i think of it.

**Comment by SirMallard** [comment]
Yeah, it would be nice, but there are other examples of where returning the disconnect callback is perfectly fine.
