### ISSUE TITLE
Add Keybinds

### ISSUE THREAD

**Issue by warprbx** [Michael-48/Iris#66]
Keybinds are missing ![image](https://github.com/user-attachments/assets/7c57371f-a210-4f5a-9119-4e02414d1ea9)

**Comment by SirMallard** [comment]
Could you be a bit more specific as to which keybinds are missing and where. Is this for a menu or something else? I'm not sure what you are referring to.

**Comment by warprbx** [comment]
Hey! I meant like when I was using this ui library there was some features where a button can turn on a check box but none for keybinds. For example, if I want to turn on a check box by pressing "S", there's no way for me to do that

**Comment by SirMallard** [comment]
This is by design. Iris is meant more for mouse navigation rather than binding
