### ISSUE TITLE
Iris.Alignment

### ISSUE THREAD

**Issue by warprbx** [Michael-48/Iris#68]
So i don't know if you can do this, but allowing for images to be aligned would be nice ![image](https://github.com/user-attachments/assets/8c02cadb-1c6c-4b0f-8762-487c18946357)
as well as widgets like text labels and buttons ![image](https://github.com/user-attachments/assets/47c7f66a-6ec1-4563-9f80-3cec0fd3e95b)
as seen here you can see that the button is as long as the ui window size, and i don't know if there's a long button widget but if not adding that would be nice

**Comment by SirMallard** [comment]
It's an interesting idea and something which Dear ImGui does have, but also work to do. The Images allow scale sizing which I'm not sure whether was a good idea to allow, but fullscreen positioning is not a bad idea.

As for the button widths a size property could be added as a minimum size.

**Comment by SirMallard** [comment]
Buttons now support a minimum size argument, added in 1e78042b5668932698b75d24d20660c510851c78.
