### ISSUE TITLE
Notification + Font Selector

### ISSUE THREAD

**Issue by warprbx** [Michael-48/Iris#69]
I don't know if there's any built in, i think that this isn't that hard to make manually but making it built in would be cool.
smth like
text
divider
more text

and a font selector that's a dropdown and lets you change the font currently being used, i know you can do it manually but a dropdown in the style editor perhaps would be cool

**Comment by SirMallard** [comment]
I don't think we'll support a Roblox style toast notification but when modals are added they might be what you are looking for.

As for the font selector, I'll redesign the style editor to include this.

**Comment by SirMallard** [comment]
I've redesigned the style editor to include a section on fonts in a56b043a348af1f6e071142bb25a147fe416ba40. This isn't an update that will come out soon though, so if you want to see it, you'll need to build it yourself.
